# Generated by Django 5.2.3 on 2025-08-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_underwear_size', '0001_initial'),
        ('product_underwear_variant', '0002_remove_productunderwearvariant_cup_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnderwearUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_size.productunderwearsize')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_variant.productunderwearvariant')),
            ],
        ),
    ]
