# Generated by Django 5.2.3 on 2025-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_underwear_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunderwearmodel',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
