# Generated by Django 5.2.3 on 2025-07-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_underwear_color', '0001_initial'),
        ('product_underwear_gender', '0001_initial'),
        ('product_underwear_image', '0001_initial'),
        ('product_underwear_model', '0001_initial'),
        ('product_underwear_size', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnderwearVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_color.productunderwearcolor')),
                ('cup_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_underwear_gender.productunderweargender')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_underwear_image.productunderwearimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_model.productunderwearmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_size.productunderwearsize')),
            ],
        ),
    ]
