# Generated by Django 5.2.4 on 2025-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
