# Generated by Django 5.2.3 on 2025-09-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbraimage',
            name='name',
            field=models.CharField(default='test', max_length=300),
        ),
    ]
