# Generated by Django 5.1.4 on 2025-07-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_color_underwear', '0001_initial'),
        ('product_image_underwear', '0001_initial'),
        ('product_model_underwear', '0002_productmodel_gender'),
        ('product_size_underwear', '0001_initial'),
        ('product_variant_underwear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_color_underwear.productcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_image_underwear.productimage'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_model_underwear.productmodel'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_size_underwear.productsize'),
        ),
    ]
