# Generated by Django 5.1.4 on 2025-07-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_gender_underwear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgender',
            old_name='color',
            new_name='gender',
        ),
    ]
