# Generated by Django 5.2.3 on 2025-06-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shiping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiping.adres'),
        ),
    ]
