# Generated by Django 5.2.3 on 2025-09-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbramodel',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productbramodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
