# Generated by Django 5.2.3 on 2025-09-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_model', '0002_alter_productbramodel_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbramodel',
            old_name='desc',
            new_name='description',
        ),
    ]
