# Generated by Django 5.2.3 on 2025-09-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_underwear_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunderwearunit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
