# Generated by Django 5.1.4 on 2025-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model_underwear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
