# Generated by Django 5.1.4 on 2025-07-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_gender_underwear', '0001_initial'),
        ('product_model_underwear', '0002_productmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_gender_underwear.productgender'),
        ),
    ]
