# Generated by Django 5.2.3 on 2025-07-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_variant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbravariant',
            name='cup_size',
        ),
        migrations.RemoveField(
            model_name='productbravariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productbravariant',
            name='stock',
        ),
    ]
