# Generated by Django 5.1.4 on 2025-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
            ],
        ),
    ]
