# Generated by Django 5.1.4 on 2025-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_image_bra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bra_product_image/'),
        ),
    ]
