# Generated by Django 5.2.3 on 2025-07-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_bra_cup_size', '0001_initial'),
        ('product_bra_variant', '0002_remove_productbravariant_cup_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBraCupSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_cup_size.productbracupsize')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_variant.productbravariant')),
            ],
        ),
    ]
