# Generated by Django 5.2.3 on 2025-09-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_cup_size', '0001_initial'),
        ('product_bra_size', '0001_initial'),
        ('product_bra_unit', '0001_initial'),
        ('product_bra_variant', '0002_remove_productbravariant_cup_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBraUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cup_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_cup_size.productbracupsize')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_size.productbrasize')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_variant.productbravariant')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductBraCupSizeVariant',
        ),
    ]
