# Generated by Django 5.1.4 on 2025-07-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_color_bra', '0001_initial'),
        ('product_image_bra', '0001_initial'),
        ('product_model_bra', '0001_initial'),
        ('product_size_bra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_color_bra.productcolor')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_image_bra.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_model_bra.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_size_bra.productsize')),
            ],
        ),
    ]
