# Generated by Django 5.1.4 on 2025-07-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cup_size_bra', '0001_initial'),
        ('product_variant_bra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cup_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_cup_size_bra.productcupsize'),
        ),
    ]
