# Generated by Django 5.2.3 on 2025-08-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_underwear_gender', '0001_initial'),
        ('product_underwear_model', '0002_productunderwearmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunderwearmodel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_underwear_gender.productunderweargender'),
        ),
    ]
