# Generated by Django 5.2.3 on 2025-07-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_bra_cup_size_variant', '0001_initial'),
        ('product_bra_size', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBraUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_size.productbrasize')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_cup_size_variant.productbracupsizevariant')),
            ],
        ),
    ]
