# Generated by Django 5.2.3 on 2025-09-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_unit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbraunit',
            old_name='variant',
            new_name='cup_size_variant',
        ),
    ]
