# Generated by Django 5.2.4 on 2025-07-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_color', '0001_initial'),
        ('product_image', '0001_initial'),
        ('product_model', '0001_initial'),
        ('product_size', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_color.productcolor')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_image.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_model.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_size.productsize')),
            ],
        ),
    ]
