# Generated by Django 5.2.3 on 2025-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_bra_color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbracolor',
            name='color',
            field=models.CharField(max_length=300),
        ),
    ]
