# Generated by Django 5.2.3 on 2025-07-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_bra_color', '0001_initial'),
        ('product_bra_cup_size', '0001_initial'),
        ('product_bra_image', '0001_initial'),
        ('product_bra_model', '0001_initial'),
        ('product_bra_size', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBraVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_color.productbracolor')),
                ('cup_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_bra_cup_size.productbracupsize')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_bra_image.productbraimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_model.productbramodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_bra_size.productbrasize')),
            ],
        ),
    ]
