# Generated by Django 5.2.3 on 2025-08-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_underwear_variant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunderwearvariant',
            name='cup_size',
        ),
        migrations.RemoveField(
            model_name='productunderwearvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productunderwearvariant',
            name='stock',
        ),
    ]
